// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOc8N-0dWadZAGMQRn5DWKhrE4oIvqzNw',
    appId: '1:310917541984:web:6ad2aebf53019080321305',
    messagingSenderId: '310917541984',
    projectId: 'your-manager-bc',
    authDomain: 'your-manager-bc.firebaseapp.com',
    storageBucket: 'your-manager-bc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqrzap8Ws5LP1taspDgg62Q99IEDqI4AA',
    appId: '1:310917541984:android:fc929d02546793f2321305',
    messagingSenderId: '310917541984',
    projectId: 'your-manager-bc',
    storageBucket: 'your-manager-bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGO10PlysuEVUGYbMHd4_niVKJ337Lt2A',
    appId: '1:310917541984:ios:82d5a6577fbcf768321305',
    messagingSenderId: '310917541984',
    projectId: 'your-manager-bc',
    storageBucket: 'your-manager-bc.appspot.com',
    iosBundleId: 'com.example.yourmanager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGO10PlysuEVUGYbMHd4_niVKJ337Lt2A',
    appId: '1:310917541984:ios:82d5a6577fbcf768321305',
    messagingSenderId: '310917541984',
    projectId: 'your-manager-bc',
    storageBucket: 'your-manager-bc.appspot.com',
    iosBundleId: 'com.example.yourmanager',
  );
}
